package com.tfkfan.bot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubscriberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriberAllPropertiesEquals(Subscriber expected, Subscriber actual) {
        assertSubscriberAutoGeneratedPropertiesEquals(expected, actual);
        assertSubscriberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriberAllUpdatablePropertiesEquals(Subscriber expected, Subscriber actual) {
        assertSubscriberUpdatableFieldsEquals(expected, actual);
        assertSubscriberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriberAutoGeneratedPropertiesEquals(Subscriber expected, Subscriber actual) {
        assertThat(expected)
            .as("Verify Subscriber auto generated properties")
            .satisfies(e -> assertThat(e.id).as("check id").isEqualTo(actual.id));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriberUpdatableFieldsEquals(Subscriber expected, Subscriber actual) {
        assertThat(expected)
            .as("Verify Subscriber relevant properties")
            .satisfies(e -> assertThat(e.active).as("check active").isEqualTo(actual.active));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubscriberUpdatableRelationshipsEquals(Subscriber expected, Subscriber actual) {}
}
